version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - appnet
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend-vue
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - appnet
    volumes:
      - ./frontend-vue:/app
      - /app/node_modules   # 避免覆蓋容器內 node_modules
    command: npm run dev

  mysql:
    image: mysql:8.3
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: announce
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
