spring:
  datasource:
    url: jdbc:mysql://mysql:3306/announce?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: appuser
    password: apppass
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always